# Usar una imagen base de Node.js
FROM node:22

# Directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos JSON al contenedor
COPY ./archivosJson/db.json /usr/src/app/api-data 
COPY ./scriptJson.sh /usr/src/app/scriptJson.sh

#darle permisos de ejecucion al script
RUN chmod +x /usr/src/app/scriptJson.sh

# Instalar json-server globalmente
RUN npm install -g json-server

# Exponer los puertos en los que se va a ejecutar json-server
EXPOSE 3000

CMD ["/usr/src/app/scriptJson.sh"]