name: Destroy Terraform

on:
  workflow_dispatch:   

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: "us-east-1"

    - name: Terraform Init
      run: terraform init  
      working-directory: ArchivosTf

    # Descargar los artefactos que contienen el nombre del bucket y el repositorio ECR
    - name: Descargar artefactos
      uses: actions/download-artifact@v4.1.8
      with:
        name: bucket_name.txt
        path: ./terraform_outputs 

    - name: Descargar artefactos
      uses: actions/download-artifact@v4.1.8
      with:
        name: ecr_name.txt
        path: ./terraform_outputs    

    #- name: Descargar tfstate desde el bucket de S3
    #  run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/terraform.tfstate terraform.tfstate --region us-east-1
    #  working-directory: ArchivosTf

    - name: Descargar tfstate desde el bucket de S3
      run: |
        S3_BUCKET_NAME=$(cat ./terraform_outputs/bucket_name.txt)
        aws s3 cp s3://$S3_BUCKET_NAME/terraform.tfstate terraform.tfstate --region us-east-1  
      working-directory: ArchivosTf  

    #- name: Vaciar el bucket de S3 antes de destruirlo
    #  run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive --region us-east-1  

    - name: Vaciar el bucket de S3 antes de destruirlo
      run: |
        S3_BUCKET_NAME=$(cat ./terraform_outputs/bucket_name.txt)
        aws s3 rm s3://$S3_BUCKET_NAME/ --recursive --region us-east-1    

   # Vaciar el repositorio ECR
    - name: Vaciar repositorio ECR
      run: |
        ECR_REPO_NAME=$(cat ./terraform_outputs/ecr_name.txt)
        
        IMAGE_IDS=$(aws ecr list-images --repository-name $ECR_REPO_NAME --query 'imageIds[*].imageDigest' --output text --region us-east-1)

        if [ -n "$IMAGE_IDS" ]; then
          aws ecr batch-delete-image --repository-name $ECR_REPO_NAME --image-ids imageDigest=$IMAGE_IDS --region us-east-1
        fi

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ArchivosTf

    - name: Eliminar el archivo terraform.tfstate del repositorio
      run: rm terraform.tfstate 
      working-directory: ArchivosTf
